name: Auto Deploy to Replit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Replit
        run: |
          curl -X POST "https://api.replit.com/v0/deploy" \
          -H "Authorization: Bearer ${{ secrets.REPLIT_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
